const createPractice = async (req, res, next) => {
  try {
    let output = await Prac;
  } catch (error) {}
};
